title: Eric Nussbaum
description: >
  <p>Economics PhD Student<br>
  University of Toronto</p>

  <p><a href="/research.html">Research</a></p>
  <p><a href="/cv.pdf">CV</a></p>

  <p><strong>Links</strong><br>
  <a href="mailto:your.email@utoronto.ca">Email</a><br>
  <a href="https://scholar.google.ca/citations?user=tutrmKIAAAAJ&hl=en">Google Scholar</a></p>
show_downloads: false
theme: jekyll-theme-minimal
