title: Eric Nussbaum
logo: headshot.jpg
description: >
  Economics PhD Student, University of Toronto.
  
  Research interests: industrial organization,
  environmental economics, and international trade.
show_downloads: false
theme: jekyll-theme-minimal
