title: Eric Nussbaum
description: >
  <p>Economics PhD Student<br>
  University of Toronto</p>

  <div class="sidebar-nav">
    <p><a href="/research">Research</a></p>
    <p><a href="/cv.pdf">CV</a></p>
  </div>

  <p><strong>Links</strong><br>
  <a href="mailto:eric.nussbaum@mail.utoronto.ca">Email</a><br>
  <a href="https://scholar.google.ca/citations?user=tutrmKIAAAAJ&hl=en">Google Scholar</a></p>
show_downloads: false
theme: jekyll-theme-minimal
